### ISSUE TITLE
Retrying stagedata should not start over

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/lando-util#32]
If staging data fails for some reason all files are restaged when the job is retried.
Instead we should be able to verify files that have already been staged similar to how ddsclient works.

**Comment by dleehr** [comment]
I'm encountering this issue pretty severely today.

After building a GKE cluster and configuring for bespin, I cannot get data staged. There are 48 files, about 4GB each. The stage data Job begins but fails early on with a `Connection reset by peer`

```
Staging 50 items.
Downloading URL https://github.com/bespin-workflows/exomeseq-gatk4/archive/v2.0.1.zip to /bespin/job-data/workflow/v2.0.1.zip.
Unzip file /bespin/job-data/workflow/v2.0.1.zip to /bespin/job-data/workflow.
Writing file /bespin/job-data/job-order.json.
Downloading DukeDS file REMOVED1.fastq.gz.
Downloading DukeDS file REMOVED2.fastq.gz..
Downloading DukeDS file REMOVED3.fastq.gz..
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/lando_util/stagedata.py", line 86, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/app/lando_util/stagedata.py", line 80, in main
    downloaded_metadata_items = stage_data(dds_client, stage_items)
  File "/app/lando_util/stagedata.py", line 28, in stage_data
    metadata_item = download_dukeds_file(dds_client, source, dest)
  File "/app/lando_util/stagedata.py", line 46, in download_dukeds_file
    dds_file.download_to_path(dest)
  File "/usr/local/lib/python3.6/site-packages/ddsc/sdk/client.py", line 397, in download_to_path
    file_url_downloader.run()
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/download.py", line 218, in run
    self.download_files()
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/download.py", line 244, in download_files
    self.download_large_files(large_files)
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/download.py", line 266, in download_large_files
    task_runner.run()
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/parallel.py", line 139, in run
    done_task_and_result = self.executor.wait_for_tasks()
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/parallel.py", line 202, in wait_for_tasks
    self.process_all_messages_in_queue()
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/parallel.py", line 231, in process_all_messages_in_queue
    keep_checking = self.process_single_message_from_queue()
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/parallel.py", line 242, in process_single_message_from_queue
    task.on_message(data)
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/parallel.py", line 60, in on_message
    self.command.on_message(data)
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/download.py", line 369, in on_message
    raise ValueError(message_value)
ValueError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 397, in _error_catcher
    yield
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 479, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 531, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 496, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 415, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/download.py", line 404, in run
    return self.retry_download_loop()
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/download.py", line 417, in retry_download_loop
    self.download_chunk(url, headers)
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/download.py", line 459, in download_chunk
    self._write_response_to_file(response)
  File "/usr/local/lib/python3.6/site-packages/ddsc/core/download.py", line 469, in _write_response_to_file
    for chunk in response.iter_content(chunk_size=self.bytes_per_chunk):
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by dleehr** [comment]
I've restarted the job several times and cannot get the data staging to get past the first few files. These files are coming from the S3 appliance. Data staging of system data (maybe on swift?) seems to be ok.

**Comment by johnbradley** [comment]
The system data (`bespin_datasets`) is stored on S3.

**Comment by dleehr** [comment]
Hmm. then I don't know why this one is having so much trouble.

**Comment by dleehr** [comment]
Looks like the stage system data is running lando-util 0.5.3 but the stage job data is 0.5.2. Also the system data container doesn't request specific resources but the job data one is 1 CPU and 2 GB RAM

**Comment by dleehr** [comment]
I started another job (189 on dev), pulling the DDS data from a project backed by Swift (not S3). it's downloaded 5 files so far without issue.
